

== Doctrine Extensions

Accedere al DB tramite Doctrine è un passo avanti rispetto a scrivere le query una ad una, però è possibile spingersi oltre e automatizzare altre operazioni, come:

-   memorizzare in una colonna la *data di creazione/modifica* di una Entity;
-   memorizzare in una colonna l'*utente* che ha creato/modificato una Entity;
-   memorizzare tutte le versioni di una Entity, cioè *tutte le modifiche* che ha subito nella sua storia (!).

Queste e molte altre operazioni possono essere agevolate o rese *trasparenti* grazie a un pacchetto chiamato *_((Doctrine Extensions))_*.

=== Installiamo il bundle

[IMPORTANT]
====
Nel momento in cui scrivo, il pacchetto ufficiale non è compatibile con Symfony 5.2, per cui dovremo usare un fix temporaneo footnote:doctrinexfix[Le istruzioni per il fix temporaneo delle Doctrine Extensions è descritto qui: <https://github.com/antishov/StofDoctrineExtensionsBundle/issues/23#issuecomment-685991439>] per poterlo installare. +
Prima di procedere consiglio caldamente di *effettuare un commit* dei sorgenti con git: se usate la shell, dal *tuo computer* date i comandi:

[source,bash]
----
cd ${PERCORSO_DI_GUYBRUSH}
git add .
git commit -m "Work in progress"
----

====

****
.icon:fas-rocket[] Se state usando Symfony 5.0 o 4.x
[NOTE]
====
Se non hai seguito il corso alla lettera, e/o state usando la versione 5.0 o 4.x di Symfony, potete dare semplicemente il comando (dal container *guybrush_php8*):

[source,bash]
----
composer require antishov/doctrine-extensions-bundle
----

Quando il comando chiede `Do you want to execute this recipe?` rispondete kbd:[y]. +
Potrete poi passare a <<stof_config,configurare>> le _Doctrine extensions_.
====
****

Dalla shell del container digitiamo questi comandi, *ignorando* gli avvisi che compariranno alla fine del primo: essi sono causati dal fatto che stiamo rimuovendo Doctrine ma *non tutti* i file di configurazione Yaml che si riferiscono a Doctrine.

[source,bash]
----
composer remove doctrine/orm doctrine/doctrine-bundle doctrine/doctrine-migrations-bundle
composer require doctrine/orm doctrine/doctrine-bundle doctrine/doctrine-migrations-bundle --ignore-platform-reqs
composer require stof/doctrine-extensions-bundle --ignore-platform-reqs
----

L'ultimo comando dovrebbe produrre questa richiesta:

----
Symfony operations: 1 recipe (ef59f8548342760d93186d01b92a98a5)
  -  WARNING  stof/doctrine-extensions-bundle (>=1.2): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/stof/doctrine-extensions-bundle/1.2

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n): 
----

Per installare il _Bundle_ digitiamo kbd:[y] e quindi kbd:[Invio]. +
A questo punto avremo sovrascritto alcuni file che dovremo ripristinare dall'ultimo commit di git. Dalla shell *non del container* ma del *nostro computer*, nella cartella *guybrush* digitiamo il comando:

[source,bash]
----
git checkout -- config/packages/doctrine.yaml migrations/.gitignore .env
----

ifeval::["{virtual}" == "Vagrant"]
// Vagrant stuff

[TIP]
.Troubleshooting
====
Il comando può fallire con un messaggio di errore simile a questo:

----
Script cache:clear returned with error code 1
!!
!!  In Filesystem.php line 182:
!!
!!    Failed to remove directory "/vagrant/var/cache/de~/pools": unlink(/vagrant/
!!    var/cache/dev/ContainerHhon5ni.legacy): No such file or directory.
!!
!!
----

Se succede, l'installazione dovrà essere effettuata nuovamente. +
Tipicamente questo errore dipende da un problema di permessi che 
*non è possibile risolvere dal container *guybrush_php8**, per cui _prima_ di lanciare 
nuovamente lo stesso comando, cancelliamo (per sicurezza) la 
sotto-directory `var/cache/de~` del progetto Symfony (può chiamarsi
anche `var/cache/de_`), stavolta _non_ dal container *guybrush_php8*, ma *dal nostro computer*.

Dopodiché possiamo ritentare l'installazione dando nuovamente il comando:

[source,bash]
----
composer require stof/doctrine-extensions-bundle
----
====
endif::[]

(((Timestampable))) (((Doctrine Extensions, Timestampable))) 
[#stof_config]
=== Configuriamo l'estensione Timestampable

Utilizzando l'estensione ((Gedmo)) _Timestampable_ è possibile memorizzare automaticamente la data di *creazione* di un record, la sua data di *modifica*, e/o la data in cui _specifici campi_ del record sono stati modificati. +
Questa estensione popola in automatico campi di tipo *date* e *datetime*,che corrispondono a oggetti PHP di tipo *DateTime* (v. la <<gedmo_timestampable,documentazione ufficiale>>).

Per usare l'estensione *Timestampable* bisogna impostare a *true* la chiave di configurazione `stof_doctrine_extensions/orm/default/timestampable`. Apriamo il file *config/packages/stof_doctrine_extensions.yaml* e modifichiamolo come segue.

[source, diff]
.config/packages/stof_doctrine_extensions.yaml
----
 # Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
 # See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
 stof_doctrine_extensions:
     default_locale: en_US
+    orm:
+        default:
+            timestampable: true
----

[TIP]
.Attenzione agli spazi
====
L'_indentazione_ nei file *Yaml* è fondamentale, e va fatta usando sempre lo stesso numero di *spazi*, senza usare caratteri di tabulazione. 
Nel codice qui sopra l'indentazione è di _quattro spazi_: la parola `orm:` dovrà essere preceduta da *quattro* spazi, e le righe successive dovranno 
essere staccate di quattro ulteriori spazi ciascuna.
====

[#timestampable_field]
== Creiamo un campo _Timestampable_

Ora aggiungiamo alla entity *Poi* un campo di tipo _datetime_ che conterrà la data di ultima modifica del record. Come spiegato nella relativa 
<<doctrine_aggiungere_campi,appendice>>, per aggiungere campi a una Entity esistente possiamo usare lo stesso comando che abbiamo usato per _crearla_,
cioè `make:entity`.

[source,bash]
----
php bin/console make:entity Poi
----

Rispondiamo come segue alle domande del _console command_:

----
 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > updatedAt

 Field type (enter ? to see all types) [datetime]:
 > 

 Can this field be null in the database (nullable) (yes/no) [no]:
 > yes

 updated: src/Entity/Poi.php

 Add another property? Enter the property name (or press <return> to stop adding fields):
 > 
----

TIP: hai notato niente di nuovo? +
Il comando `make:entity` è sufficientemente sveglio da capire che se il nome
di un campo finisce per *At*, può trattarsi di un campo che ha a che fare
col tempo, e propone di default il tipo _datetime_.

// Forse era un bug che è stato corretto

// :dbl_: __

// [CAUTION]
// .Troubleshooting
// ====
// Quando modifichiamo una *Entity* esistente, può succedere che il comando `make:entity` aggiunga una o più righe strane al file sorgente:

// [source,php]
// ----
//   private $__EXTRA__LINE;
//   public function setField(string $field): self
//   {
//     $this->field = $field;
//     $__EXTRA__LINE;
//     return $this;
//   }
// ----

// La fantomatica variabile `${dbl_}EXTRA{dbl_}LINE` non ha alcuna utilità; rimane lì per colpa di un bug del comando (o una _feature_ non richiesta icon:far-smile[]). In ogni caso, tutte le righe che la contengono possono essere cancellate senza timore. +
// Controlliamo se nel file `src/Entity/Poi.php` ci sono riferimenti di questo tipo e, se ce ne sono, cancelliamoli tutti prima di proseguire.
// ====

Ora annotiamo la Entity per far sì che ((Doctrine)) utilizzi la _Timestampable extension_ per popolare automaticamente il campo *updatedAt*: nel file *src/Entity/Poi.php* dopo la riga che inizia per `namespace`, aggiungiamo la direttiva:

[source,php]
----
use Gedmo\Mapping\Annotation as Gedmo;
----

Quindi, annotiamo il campo *private $updatedAt* come segue:

[source,php]
----
  /**
   * @ORM\Column(type="datetime", nullable=true)
   * @Gedmo\Timestampable(on="update")
   */
  private $updatedAt;
----

L'opzione `on` dell'annotazione comunica alla _Doctrine Extension_
la modalità da usare per popolare questo campo. Quest'opzione può assumere tre valori.

.Valori possibili di _on_
****
. `on="create"` : salva la data/ora corrente nel campo quando il record viene _creato_.

. `on="update"` : salva la data/ora corrente nel campo ogniqualvolta il record viene _salvato_ (creato o aggiornato).

. `on="change"` : salva la data/ora corrente nel campo se e solo se *specifici campi* del record vengono modificati; con questa opzione, è obbligatorio aggiungere l'opzione `field`, e specificare al suo interno l'insieme dei campi da tenere *sotto controllo*; ad es. se vogliamo che il campo venga aggiornato solo al cambiamento dei campi *title* e *body*: +
[source,php]
----
  /**
   * ...
   * @Gedmo\Timestampable(on="change", field={"title", "body"})
   */
----
****

== È tempo di migrare

Tramite i comandi `make:entity`, Symfony ha creato quattro file:

- *src/Entity/Poi.php*
- *src/Entity/PoiCategory.php*
- *src/Repository/PoiCategoryRepository.php*
- *src/Repository/PoiRepository.php*

Questi file corrispondono a due tabelle nel database, che però *non esistono* ancora. ((Doctrine)) può creare le tabelle automaticamente a partire dai file presenti in `src/Entity`: vediamo come.

[#makemigration]
=== Creare la migration

Per prima cosa va creata quella che Doctrine chiama _migration_: una classe PHP in grado di _allineare_ lo stato del database a quello dei nostri sorgenti. Questa operazione consiste nel:

. *creare* le tabelle mancanti;
. *aggiornare* le tabelle esistenti _aggiungendo_ o _eliminando_ le colonne opportune;
. *eliminare* eventuali tabelle che non servono più (perché non corrispondono a nessuna ((Entity))). +

La _creazione_ di una migration non altera il database: per modificare la struttura del DB bisogna _eseguire_ la migration. +
Per creare una _migration_, dal container *guybrush_php8* è sufficiente dare il comando:

[source,bash]
----
php bin/console make:migration
----

In questo modo viene creato un nuovo file PHP nella directory *src/Migrations*: si tratta di una classe dotata di due metodi, *up* e *down*:
*up()* esegue questa migrazione, mentre *down()* riporta il database allo stato _precedente_ a questa migrazione.

Non dovremo chiamarli direttamente: ci penserà Symfony con un altro _console command_.

=== Eseguire la _migration_

Per applicare al DB le modifiche contenute nella *migration* appena creata va dato il comando:

[source,bash]
----
php bin/console doctrine:migrations:migrate
----

Questo risponderà con un messaggio minatorio:

  WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)

Rispondiamo coraggiosamente kbd:[y] e premiamo kbd:[Invio].

Se non compaiono messaggi di errore, nel DB *guybrush* verranno create le due tabelle relative alle _Entity_: *PoiCategory* e *Poi*.

<<<
