on: workflow_dispatch
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    name: 'Build that PDF book'
    steps:
      - name: Run dockerized build script
        id: bp
        uses: actions/build-action@v2
