on: workflow_dispatch
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    name: 'Build that PDF book'
    container:
      image: asciidoctor/docker-asciidoctor:latest
      volumes:
        - "/asciidoc:/documents"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List working dir on container
        run: "ls -la /__w/symfony-storefinder-book/"
      # - name: Run dockerized build script
      #   id: bp
      #   run: "bash ./scripts/github-build-pdf.sh"
        
